### ISSUE TITLE
Prebuild binary

### ISSUE THREAD

**Issue by shamsulazhar** [pusher-community/titanium_pusher_android#2]
Hi Ruben,

Do you have the prebuilt binary version of this module?

Thanks in advance.

**Comment by demogar** [comment]
I second this. I think it would be awesome if you'd provide a zip file for the module. Anyways, I already built it on my own :)

**Comment by GabrielZuliani** [comment]
I simply cant' build this module, in Titanium it always returns an error (exec returned 2) and with ant it gives out the error CreateProcess error = 193, %1 is not an valid Win32 application. If you could provide the .zip with the PreBuilt module I'd be really grateful.

**Comment by nikhilrastogi04** [comment]
@shamsulazhar  Hi did you get this working ? If yes, can you please provide me with prebuilt binary?

**Comment by nikhilrastogi04** [comment]
Can anyone provide me prebuilt library. I am able to build this module but I am getting following error during runtime

[ERROR] :  TiApplication: (KrollRuntimeThread) [1028,1028] Sending event: exception on thread: KrollRuntimeThread msg:java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1306]:    37 cannot locate '__cxa_end_cleanup'...
[ERROR] :  TiApplication: ; Titanium 3.3.0,2014/07/11 12:36,787cd39
[ERROR] :  TiApplication: java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1306]:    37 cannot locate '__cxa_end_cleanup'...
[ERROR] :  TiApplication:
[ERROR] :  TiApplication: at java.lang.Runtime.loadLibrary(Runtime.java:370)
[ERROR] :  TiApplication: at java.lang.System.loadLibrary(System.java:535)
[ERROR] :  TiApplication: at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:114)
[ERROR] :  TiApplication: at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:81)
[ERROR] :  TiApplication: at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:175)
[ERROR] :  TiApplication: at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)
[ERROR] :  AndroidRuntime: FATAL EXCEPTION: KrollRuntimeThread
[ERROR] :  AndroidRuntime: java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1306]:    37 cannot locate '__cxa_end_cleanup'...
[ERROR] :  AndroidRuntime:
[ERROR] :  AndroidRuntime: at java.lang.Runtime.loadLibrary(Runtime.java:370)
[ERROR] :  AndroidRuntime: at java.lang.System.loadLibrary(System.java:535)
[ERROR] :  AndroidRuntime: at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:114)
[ERROR] :  AndroidRuntime: at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:81)
[ERROR] :  AndroidRuntime: at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:175)
[ERROR] :  AndroidRuntime: at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)
